version: '3.7'
services:
  blog-mongo-spring:
    image: "mongo"
    container_name: "blog-mongo-spring"
    volumes:
      - /home/ec2-user/data:/data/db
    ports:
      - 27017:27017

  blog-spring:
    image: blog-spring:1.0
    build: .
    container_name: blog-spring
    ports:
      - 8080:8080
    environment:
      DB_SERVER: blog-mongo-spring
    links:
      - blog-mongo-spring

